<a href="https://colab.research.google.com/github/Legacy560/MLTSA25_RWolynetz/blob/main/inclasscode/python_bootcamp_MLTSA25_RWolynetz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_str = "hello"


In [41]:
type(my_str)

str

In [3]:
print(my_str)

hello


In [4]:
my_int = 36

In [5]:
type(my_int)

int

In [7]:
my_float = 36.
type(my_float)

float

In [8]:
print(my_float)

36.0


In [9]:
my_int*my_float

1296.0

In [10]:
my_int * my_str

'hellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohello'

In [13]:
helloWorld = "Hello" + " World!"
print(helloWorld)

Hello World!


In [15]:
import numpy as np #The only package that has a paper on nature

In [17]:
myNparr = np.array([1,2,3])
myNparr

array([1, 2, 3])

In [18]:
my_int * myNparr

array([ 36,  72, 108])

In [19]:
my_bool = True

In [20]:
0==1

False

In [21]:
my_int == 1

False

In [22]:
my_int != 6

True

In [23]:
if my_int != 6:
  print("my_int is not equal to 6")
else:
  print("it was 6")
  #remember python is indentation-sensitive

my_int is not equal to 6


In [24]:
type(my_int)

int

In [26]:
myNparr.dtype #attribute

dtype('int64')

In [27]:
myNparr.max()

3

In [28]:
myNparr.argmax() #returns location of largest number

2

In [31]:
myNparr[2]

3

In [30]:
myNparr[-1]

3

In [32]:
myNparr[1:] #Colon indicates a range. Allows us to select a subset of the dataset. This starts at index 1 and goes to the end.

array([2, 3])

In [33]:
myNparr[1:3]

array([2, 3])

In [35]:
list(range(1,4))

[1, 2, 3]

In [36]:
for a in range(1,4):
  print(sum(np.arange(0,a)))
  #arange returns a range as a numpy array

0
1
3


In [40]:
def allOds(lastNum):
  """
  Finds(prints) all odd numbers between 0 and lastNum
  input:
    lastNum: (int) last number in list
  Return:
    a list of odd numbers

  """
  odds = []
  for i in range(0,lastNum+1):
    if i % 2 == 1:
      odds.append(i)
      #print(odds)
  return odds
allOds(10)


[1, 3, 5, 7, 9]

In [38]:
allOds? #Returns docstring of the function.

# Exercise:
Create a function that takes a word and checks if it's a palindrome.


In [59]:
def checkPali(word):
  """
  Checks if word is palindrome.
  Input:
    word(str): imput word
  Output:
    True if palindrome. False otherwise.
  """

  #Check if word is string
  '''
  if(type(word) != str):
    print("Not a string")
    '''
  assert type(word) == str, "Not a string" #This prints not a string if word is not a string.
  if word == word[::-1].lower(): #Python is case-sensitive.
    return True
  else:
    return False
  return



In [58]:
checkPali(9)

AssertionError: Not a string

In [55]:
word = "racecar"
word[::-1]

'racecar'